Windows execution and build fix
BitPhinix/slate-yjs-example pull request #84
Opened 2021-07-20 12:11 UTC by schlenger

- Use a eslint configuration that supports Windows platforms
- Use shx to execute UNIX commands on Windows machines
- Updated browser list

2021-07-20 12:12 UTC, schlenger commented
s. https://github.com/BitPhinix/slate-yjs-example/issues/83

2021-07-20 12:12 UTC, schlenger commented
Also I've updated the readme according to the other issue here https://github.com/BitPhinix/slate-yjs-example/issues/82

2021-08-10 08:31 UTC, schlenger commented
@BitPhinix Any suggestions or missing things?

2021-08-10 08:37 UTC, BitPhinix requested changes
Thanks so much and sorry for not looking into this sooner. It got a bit lost in my GitHub notifications. Just one small change and then we are ready to go 🚀

2021-08-10 08:37 UTC, BitPhinix commented on .eslintrc.js
> +        endOfLine: 'auto',
I'm not a fan of having this set set to auto since this is something that can be fixed with a setting in your text editor/ide (see [here for vscode](https://medium.com/@csmunuku/windows-and-linux-eol-sequence-configure-vs-code-and-git-37be98ef71df#:~:text=VS%20Code%20%3D%3E%20Settings%20%3D%3E,new%20files%20that%20you%20create.)). We might want to add this to the readme as well

2021-08-10 08:51 UTC, schlenger commented on .eslintrc.js
> +        endOfLine: 'auto',
Okay. Yes, I'm with you. I'll change this and update the readme file accordingly.

Thanks for the feedback :)

2021-08-11 21:10 UTC, BitPhinix requested changes

2021-08-11 21:10 UTC, BitPhinix commented on README.md
> +correctly. You can also configure prettier according to your needs by adding the following lines to your `.eslintrc.js`:
I'm not a huge fan of recommending changing the eslint config here since that would make contributing back to the repository harder (You’d have to change it back and the reformat all files)

2021-08-11 21:10 UTC, BitPhinix commented on .eslintrc.js
> +module.exports = {
I’m a bit confused why this many lines show up in the git diff, did you commit with different line breaks?

2021-08-12 08:59 UTC, schlenger commented on README.md
> +correctly. You can also configure prettier according to your needs by adding the following lines to your `.eslintrc.js`:
Okay, I removed this hint.

2021-08-12 09:00 UTC, schlenger commented on .eslintrc.js
> +module.exports = {
Ironically, yes ;) I've changed this here and in the readme file. Thanks for pointing this out.

2021-08-12 09:49 UTC, BitPhinix approved these changes
Thank you so much again 🙏

2021-08-12 09:53 UTC, BitPhinix commented
There seems to be a lint issue in the eslint config 😄. You should be able to fix using `eslint --fix`

2021-08-14 16:29 UTC, merged